"""Them Address model (fix ten constraint)

Revision ID: 2693b0c55eca
Revises: 4e0e1a2e5a05
Create Date: 2025-11-11 17:32:26.681649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2693b0c55eca'
down_revision = '4e0e1a2e5a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_orders_shipping_address', 'address', ['shipping_address_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_shipping_address', type_='foreignkey')
        batch_op.drop_column('shipping_address_id')

    # ### end Alembic commands ###
